### ISSUE TITLE
Add mutex versions of profile_model and boundary_model.

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#102]
We currently have routines that have been customized for LVCMS.  But other any users working in a multi-threaded environment are going to need these as well.  Let's take the LVCMS routines and make a generic version that is based on the boost::thread library.

**Comment by islanderjtn** [comment]
Added boundary_lock and profile_lock classes to the ocean package. These classes add a mutex to all methods of the boundary_model and the profile_model.
