### ISSUE TITLE
Memory leaks in boundary_lock_test and profile_lock_test.

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#104]
These test the ability of multiple threads to access a common set of environmental data.  However, the tests have no way of knowing when both threads have been completed, so they don't delete the environmental data when the test is complete.

**Comment by islanderjtn** [comment]
Resolved memory leak issues of #104. Rewrote boundary_lock_test(s) and
profile_lock_test(s) to use boost::thread_group and boost::bind vs the
overloaded operator()() functor.
