### ISSUE TITLE
Compute sensor_pair subsets for the retrieval of fathometer and eigenverb returns. 

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#134]
As discussed in section 2.9 of the Eigenverb software design document
- The sonar training system passes a list of sensors and their current mode of operations: source, receiver, or both.
- The reverberation model passes this list of sensors and modes to the ```sensor_pair_manager```.
- The ```sensor_pair_manager``` finds all ```sensor_pair``` objects that include these sensors in the specified modes.

**Comment by islanderjtn** [comment]
Implemented sensor_pair_manager::find_pairs which takes in a sensor _query_map.
