### ISSUE TITLE
Implement the eigenverb portions of sensor::run_wave_generator()

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#136]
As specified in section 2.6 compute propagation effects portion of SDD.

**Comment by campreilly** [comment]
The goal of this effort is to have wavefront_generator produce eigenverbs and store those eigenverbs in the sensor_pair object.  It should include a test that compares the eigenverb values produced by reverb_analytic_test are close to those produced by eigenverb_test/eigenverb_basic.

**Comment by islanderjtn** [comment]
Closed in Pull Request #199.
