### ISSUE TITLE
Add data structure/class to return the eigenray_lists from sensor_pair_manager.

### ISSUE THREAD

**Issue by islanderjtn** [campreilly/UnderSeaModelingLibrary#138]
Presently data structure returned from get_fathometers call of sensor_pair_manager is an eigenray_collection.   This needs to be changed to a list or vector of structures that contain the following:
Src Position
Rcv Position
DistanceFromSensorTL's
DepthOffsetFromSensorTL's
eigenray_list

See DiscreateData for more info.

**Comment by campreilly** [comment]
I wonder if we'll need to do something similar for eigenverb_collections.

**Comment by campreilly** [comment]
To support integration testing, I think it would be a good idea if this class had the ability to save itself to a netCDF file.

**Comment by islanderjtn** [comment]
Implemented fathometer_model class.
