### ISSUE TITLE
Adapt reverb_analytic_test to a realistic monostatic scenario

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#154]
These studies act as our integration tests for case that are too complex to test in isolation.  Their results will also be delivered as part of the verification tests that accompany the reverberation release.

The structure of the reverb_analytic_test breaks this integration into a series of steps that can be isolated during integration:
```
		define_ocean_characteristics();
		define_sensor_characteristics();
		deploy_sensor_instance();     // starts reverb calc `
		wait_for_results();
```
But other than that, it is doing the same basic job that reverberation_monostatic is doing.

**Comment by Tibonium** [comment]
Removing from public repo
