### ISSUE TITLE
Develop a beam_pattern_model that combines different horizontal and vertical patterns.

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#156]
Some test cases use a beam pattern that is a combination of different types in the horizontal and vertical direction.  For example, it might use a For example a beam_pattern_grid in the vertical but a beam_pattern_solid in the horizontal.

**Comment by Tibonium** [comment]
Is this any different them simply multiplying two beam patterns together?

The information contained in this message, and any attachments, may contain privileged and/or proprietary information that is intended solely for the person or entity to which it is addressed. Moreover, it may contain export restricted technical data controlled by Export Administration Regulations (EAR) or the International Traffic in Arms Regulations (ITAR). Any review, retransmission, dissemination, or re-export to foreign or domestic entities by anyone other than the intended recipient in accordance with EAR and/or ITAR regulations is prohibited.

**Comment by campreilly** [comment]
Yes, the patterns should just be multiplied together.

**Comment by Tibonium** [comment]
Tests have yet to be added for these new classes.
