### ISSUE TITLE
Use spreading_hybrid_gaussian computation of intensity for eigenverb intensities

### ISSUE THREAD

**Issue by Tibonium** [campreilly/UnderSeaModelingLibrary#162]
In order to use spreading hybrid gaussian, the incident ray requires a neighbor ray to the +1 and -1 directions, the current wave on_edge logic accounts for this when building eigenrays. However, all rays should be valid rays to make an eigenverb from, but as the spreading model requires the neighbor support, we run into issues when creating an eigenverb from a ray on the wavefront that is at the extremes of the ray fan.

At present we do not use spreading models to compute energy for each eigenverb, but have intentions to do so in the future.

**Comment by campreilly** [comment]
This work should be combined with issue #130 .
