### ISSUE TITLE
Source parameters needs pulse length

### ISSUE THREAD

**Issue by Tibonium** [campreilly/UnderSeaModelingLibrary#171]
In order for eigenverb generator to compute reverberation, the pulse length of the signal is needed. We have discussed that this is specific to the source_params and hence need to be added to this class.

**Comment by campreilly** [comment]
Another way to handle it would be to use it as "public static" configuration variable in the evelope generation.  But that assumes that all reverberation curves use the same duration.

**Comment by campreilly** [comment]
This issue replaced by the work in #187
