### ISSUE TITLE
Interpolate frequencies

### ISSUE THREAD

**Issue by islanderjtn** [campreilly/UnderSeaModelingLibrary#174]
From #159 Propagate Frequencies the items that were not closed by Pull Request #173 .

Using the frequency property of sensor_pair:

* Use these frequencies to generate envelopes in envelope_generator.
During envelope generation, the source's eigenverbs will need to be interpolated onto the sensor_pair's list of frequencies. Only the source eigenverbs need to be done this way, as the frequencies in the list of the sensor pair are guaranteed to be in the list of frequencies for the receiver.
* When eigenrays are received from the sensor_model, they will need to be interpolated onto the sensor_pair's list of frequencies.
* When a request for reverberation data comes in from the user, the data stored in the sensor_pair will need to be interpolated to the frequencies defined in the request. These frequencies may not be the same as the ones stored in the sensor_pair.

Add the ability to cache the beam level, as a function of the frequencies stored in each sensor_pair. This prevents us from recomputing beam levels in highly multistatic scenarios.

**Comment by campreilly** [comment]
Is this the same as issue #172?

**Comment by campreilly** [comment]
Most of this work was completed as part of the relocate_frequencies branch. Parts that remain were split into their own issues.
