### ISSUE TITLE
Add pulse_length and reverb_duration to source_params constructor

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#195]
During his review of pull request #193, Ted noticed an outstanding bug.

* The source_params only added pulse_length and reverb_duration with setter's/getter's. If constructor is changed in future to handle this all additional libraries will require review, as they use the source_params constructor.

To fix this issue, we not only have to update the source_params constructor, but also ensure that the new signature is used in all of our tests.

**Comment by islanderjtn** [comment]
Studies/reverb_analytic_test needs update.
Did not test other usml_xxxxxx.libs, may also need update.

**Comment by campreilly** [comment]
I can't believe I made such a rookie mistake!
