### ISSUE TITLE
Use of seq_augment in wavefront_generator causes crash

### ISSUE THREAD

**Issue by islanderjtn** [campreilly/UnderSeaModelingLibrary#207]
While reviewing seq_augment pull request attempted to add seq_augment to wavefront_generator creation of DE's.  When running reverb_analytic_test found following crash.
seq_rayfan use is tested in sequence_test/seq_augment_test.

![capture](https://cloud.githubusercontent.com/assets/3474388/7614697/85a8eff0-f966-11e4-8b30-ef0fe3f5a743.PNG)

**Comment by campreilly** [comment]
Is it possible that some of the values in the augmented seq_rayfan are duplicates?  That would cause delta(1) to equal zero, and result in this crash.

**Comment by islanderjtn** [comment]
Reviewed output values did not see duplicates.

**Comment by Tibonium** [comment]
I am unable to reproduce this error, in either debug/release mode. Both complete just fine for me with your commented out code.
