### ISSUE TITLE
data_grid_svp fails to set interp_type when interp_type(2) != GRID_INTERP_LINEAR

### ISSUE THREAD

**Issue by JohnAAC** [campreilly/UnderSeaModelingLibrary#226]
this is from data_grid_svp.h, and I guess you should be testing interp_type(2) in the second condition.

            if ((interp_type(1) != GRID_INTERP_LINEAR)
                    || (interp_type(1) != GRID_INTERP_LINEAR)) {
                interp_type(1, GRID_INTERP_LINEAR);
                interp_type(2, GRID_INTERP_LINEAR);
            }

**Comment by JohnAAC** [comment]
Also, in the detailed comments there is a reference to "both axes" should have the same interp type.  But there are three axes.  The comment should be clarified.

**Comment by campreilly** [comment]
Do we really need the if blocks on these statements in the first place?
```
            if (interp_type(0) != GRID_INTERP_PCHIP) {
                interp_type(0, GRID_INTERP_PCHIP);
            }
            if ((interp_type(1) != GRID_INTERP_LINEAR)
                    || (interp_type(1) != GRID_INTERP_LINEAR)) {
                interp_type(1, GRID_INTERP_LINEAR);
                interp_type(2, GRID_INTERP_LINEAR);
            }
```

**Comment by JohnAAC** [comment]
Designation: Non-Finmeccanica
Seems kind of redundent.

**Comment by campreilly** [comment]
We discussed it here an agreed that they can come out.  I'll start working on this now in the release 1.0 branch.
