### ISSUE TITLE
envelope_generator::beam_gain() may only work for single beams

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#231]
In the std::copy() below, the result always seems to be put into beam_matrix.begin1().  How do the second and subsequent indices get filled in?

```
matrix<double> envelope_generator::beam_gain(
    sensor_params::beam_pattern_list beam_list,
    const seq_vector* freq, double de_rad, double az_rad, orientation orient)
{
    // beam_level requires ublas vector
    const vector<double> frequencies = *freq;

    matrix<double> beam_matrix( freq->size(), beam_list.size() ) ;

    vector<double> level( freq->size(), 0.0 ) ;

    BOOST_FOREACH( beam_pattern_model::id_type id, beam_list) {

        beam_pattern_model::reference bp = beam_pattern_map::instance()->find(id);
        bp->beam_level(de_rad, az_rad, orient, frequencies, &level ) ;

        std::copy(level.begin(), level.end(), beam_matrix.begin1());
    }

    return beam_matrix;
}
```

**Comment by Tibonium** [comment]
std::copy(source.begin(), source.end(), dest.begin())<http://en.cppreference.com/w/cpp/algorithm/copy>

**Comment by campreilly** [comment]
Sorry - I wasn't clear.  I think the point is that the destination always seems to point to beam_matrix.begin1().  Shouldn't the destination be different for each value of ```id```?  To me, it looks like we need to add an iterator for the the destination, but I could be wrong.

**Comment by campreilly** [comment]
Fixed a typo in title.
