### ISSUE TITLE
compile pow function  fail

### ISSUE THREAD

**Issue by beijihuohu1** [campreilly/UnderSeaModelingLibrary#251]
math_traits.h(718,1): error C2440: "return": Cannot convert from "std::complex" to "std::complex" (compiled source file types\wposition1.cc) 
vs2019 compile x64

**Comment by campreilly** [comment]
@beijihuohu1 - After a long time away, I'm getting ready to put out a new release of WaveQ3D. I'm looking to resolve your issue, if you are still interested. Which version of vs c++ would you like to see me try it on?
