### ISSUE TITLE
hidden-overload warning for `data_grid_svp::interpolate`

### ISSUE THREAD

**Issue by cconvey** [campreilly/UnderSeaModelingLibrary#278]
As reported by `clang++-17 -Wall`:
```
home/cconvey/r/cconvey/usml/usml/../usml/types/data_grid_svp.h:154:12: warning: 'usml::types::data_grid_svp::interpolate' hides overloaded virtual function [-Woverloaded-virtual]
  154 |     double interpolate(double* location, double* derivative = nullptr) const {
      |            ^
/home/cconvey/r/cconvey/usml/usml/../usml/types/gen_grid.h:83:15: note: hidden overloaded virtual function 'usml::types::gen_grid<3>::interpolate' declared here: type mismatch at 1st parameter ('const double *' vs 'double *')
   83 |     DATA_TYPE interpolate(const double location[],
      |               ^
```

**My guess at what's happening:**
- Although we often treat them interchangeably, `double*` and `double[]` are in fact distinct types when used as function parameters, particularly w.r.t. overload resolution.
- So in this case, your base class and derived class are actually defining different overloads of the `interpolate` method.
- That's totally legal, but C++ programmers are often surprised by how this plays out in terms of (a) overload resolution, and (b) over-ridden / virtual methods.  That's why this is a compiler warning rather than an error.

This gets into some of the gnarlier parts of the C++ spec, but here's some background:
- https://stackoverflow.com/questions/411103/function-with-same-name-but-different-signature-in-derived-class-not-found
- https://stackoverflow.com/questions/72128622/template-function-taking-array-argument-vs-overload-function-taking-pointer-argu
- section (6) on this page: https://en.cppreference.com/w/cpp/language/overload_resolution

**Ideas**
Would it make sense to just replace `location[]` with `*location` in these signatures?  I'm not sure this would work, but it might be the easiest solution if it does.

**Comment by campreilly** [comment]
Feel free to make this change.
