### ISSUE TITLE
Reverberation envelope accuracy dependence on number of rays in the rayfan

### ISSUE THREAD

**Issue by Tibonium** [campreilly/UnderSeaModelingLibrary#61]
While attempting to increase the number of rays in the rayfan to 181 the c++ implementation of eigenverb produces results of approximately 3 dB higher, or what appears to be a multiple of two in the calculations.

The matlab implementation of eigenverb was changed to demonstrate the indifference to multiplying by two and using 181 rays. The results for the matlab code yielded the same results. When the c++ implementation was compared against these results, it should a mean difference of 3 dB.

Investigation into this doubling or multiplying by two is needed.

**Comment by campreilly** [comment]
I believe that this changes that made in the envelope_accuracy branch resolve this issue.  If not, we can revisit later.  Related to issue #215.
