### ISSUE TITLE
Sequences can't be used as uBLAS vectors in some operations

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#66]
Because usml::types::seq_vector is missing some functionality, sequences can't be used as uBLAS vectors in some operations.  Example from `usml::ocean::reflect_loss_rough::reflect_loss()`

We'd like to write:

		noalias(*amplitude) = exp( ( -TWO_PI / _sound_speed
				* _wave_height * abs(sin(angle)) )
				* frequencies ) ;

But this generates errors in the form

```
/usr/local/include/boost/numeric/ublas/vector_expression.hpp: In instantiation of ‘boost::numeric::ublas::vector_reference<const usml::types::seq_vector>’:
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:1222:   instantiated from ‘boost::numeric::ublas::vector_binary_scalar1<const double, usml::types::seq_vector, boost::numeric::ublas::scalar_multiplies<double, double> >’
/home/sreilly/Projects/usml/../usml/ocean/reflect_loss_rough.h:70:   instantiated from here
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:172: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:180: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:204: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:208: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:214: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:234: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
/usr/local/include/boost/numeric/ublas/vector_expression.hpp:238: error: no type named ‘iterator’ in ‘const class usml::types::seq_vector’
```

So, instead we write:

		noalias(*amplitude) = frequencies ;	// copy sequence into vector
		noalias(*amplitude) = exp( ( -TWO_PI / _sound_speed
				* _wave_height * abs(sin(angle)) )
				* (*amplitude) ) ;

**Comment by Tibonium** [comment]
I do not believe this is possible to solve with the current implementation of seq_vector, based on

"\brief A zero vector of type \c T and a given \c size
A zero vector of type \c T and a given \c size. This is a virtual vector in the sense that no memory is allocated for storing the zero values: it still acts like any other vector. However assigning values to it will not change the zero vector into a normal vector. It must first be assigned to another normal vector by any suitable means. Its memory footprint is constant."

Which is the basis for the seq_vector class, "This design uses zero_vector<T> as a model of how to implement a read-only uBLAS vector."

**Comment by campreilly** [comment]
In this case, we aren't actually trying to assign any values to the *frequencies* vector.  I wonder why is doesn't work. Weird.  Does using a zero vector in place of the *frequencies* vector compile?

**Comment by Tibonium** [comment]
I have figured out how to do it, however, it does require that the seq_vector class be rewritten. I am trying to find a way to adapt it to be usable in usml with minimal changes, if plausible. My prototype sequence class does follow the protected data design as desired with all seq_vectors.
