### ISSUE TITLE
Upgrade NetCDF-C++ interface to cxx4 variant 

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#88]
The NetCDF library currently supports two variants of the C++ interface (see
http://www.unidata.ucar.edu/downloads/netcdf)
- Legacy NetCDF-3 C++ Source Code targball (.tar.gz) 
  - The 4.2 version of the netCDF C++ library includes no changes since the 4.1.3 release, but is provided for backwards compatibility as a separate package. It was developed before key C++ concepts like templates, namespaces, and exceptions were widely supported. It's not recommended for new projects, but it still works.
- The Latest Stable netCDF-4 C++ Release 
  - The netCDF-4 C++ version 4.2.1 release is the latest stable release supporting the netCDF-4 data model and formats.

The older interface is very kludgy and is no longer being supported.  Eventually, we need to migrate to the newer interface.  But, all of the binary distributions that we are currently working with are still using the old one.  So, an upgrade would required our users to build the new C++ interface from source.

**Comment by zcream** [comment]
Could this be checked in? It would be nice to use the newer interfaces and link with the latest netcdf.

**Comment by campreilly** [comment]
Changes complete and will be delivered in next milestone.
