### ISSUE TITLE
Investigate slowness in cmp_speed test case

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#93]
The cmp_speed results from 20131104, that we use in the JASA paper, cmp_speed running at 7.75 sec for 100 targets.  That same test is now taking 12.5 sec (using Release mode with static libraries), and we need to investigate the cause of that slowdown.  Many changes have been made to the model since that time to improve fidelity.  Are some of these changes also having a bit impact on speed?

The new test was run using:

    Reilly's Dell Latitude Laptop E6520
    Intel i5-2540M CPU @2.60 GHz
    CentOS 6.6 on Oracle VM Virtual Box under Windows 7

**Comment by Tibonium** [comment]
This issues appears to be tied to the inclusion of -std=c++98. This issue may be strongly tied to issue #38
