### ISSUE TITLE
Explicit use of std::isnan() in netcdf_profile,cc not compiling in Visual Studio 10

### ISSUE THREAD

**Issue by campreilly** [campreilly/UnderSeaModelingLibrary#96]
Visual Studio 10 claims that isnan is not a member of std:: namespace.  Was this on purpose or an oversight?

Example:  Line 156 uses `if ( ! isnan(missing) )`  but line 199 uses `if( ! std::isnan(curr) )`

I just want to check with the team before I change it.

In version 4941aff7cedeb086afe8ca297c27267ad143b7a3

**Comment by Tibonium** [comment]
This makes sense as for Visual, the isnan function is defined as _isnan() in math_traits.h
